### ISSUE TITLE
Question - Conversion to C# possible?

### ISSUE THREAD

**Issue by 99bobster99** [stas-g/findPeaks#4]
I'm new to R-Statistical and unfamiliar with the command set. 

Would it be possible to receive your program in a native format (psuedo code)? 

Even better would be C#, if possible.

I'm looking for a solution in order to find the max and min input power on a large DC motor.

**Comment by stas-g** [comment]
hi @99bobster99 ,

here is the algorithm in pseudo-code:

```
input: ordered vector x;
output: vector peaks, initiated as null vector;
set: resolution parameter m;
n = length(x);

for k in 1, 2, ..., n - 1:
  set tmp[k] = sign(x[k + 1] - x[k])

for i in 1, 2, ..., length(tmp) - 1:
  set shape = tmp[i + 1] - tmp[i]
  if shape < 0:
    if i - m + 1 > 0:
      set z = i - m + 1
    else:
      set z = 1

    if i + m + 1 < n:
      set w = i + m + 1
    else:
      set w = n

    set range = [z, z + 1,..., i, i + 2, ..., w - 1, w]
    if for all j in range x[j] <= x[i + 1]:
      peaks <- [peaks, i + 1]

return peaks
```

using that, you should be able to reproduce it in any programming language, including C#.


best,
stas

**Comment by 99bobster99** [comment]
Hi Stas,
Excellent, thank you very much!! :)

All the best!

    On Monday, November 15, 2021, 07:56:48 a.m. EST, Stasia Grinberg ***@***.***> wrote:  
 
 


hi @99bobster99 ,

here is the algorithm in pseudo-code:
input: ordered vector x;
output: vector peaks, initiated as null vector;
set: resolution parameter m;
n = length(x);

for k in 1, 2, ..., n - 1:
  set tmp[k] = sign(x[k + 1] - x[k])

for i in 1, 2, ..., length(tmp) - 1:
  set shape = tmp[i + 1] - tmp[i]
  if shape < 0:
    if i - m + 1 > 0:
      set z = i - m + 1
    else:
      set z = 1

    if i + m + 1 < n:
      set w = i + m + 1
    else:
      set w = n

    set range = [z, z + 1,..., i, i + 2, ..., w - 1, w]
    if for all j in range x[j] <= x[i + 1]:
      peaks <- [peaks, i + 1]

return peaks

using that, you should be able to reproduce it in any programming language, including C#.

best,
stas

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
